mutation CreateFoodItem($calories: Float!, $carbohydrates: Float!, $fat: Float!, $foodName: String!, $protein: Float!, $servingSize: Float, $unit: String) @auth(level: USER) {
  foodItem_insert(data: {calories: $calories, carbohydrates: $carbohydrates, fat: $fat, foodName: $foodName, protein: $protein, servingSize: $servingSize, unit: $unit})
}

query GetMealsForUser($userId: UUID!) @auth(level: USER) {
  meals(where: {userId: {eq: $userId}}) {
    id
    mealName
    mealTime
    notes
    mealEntries_on_meal {
      quantity
      foodItem {
        foodName
        calories
        fat
        carbohydrates
        protein
      }
    }
  }
}

mutation UpdateMealNotes($id: UUID!, $notes: String) @auth(level: USER) {
  meal_update(key: {id: $id}, data: {notes: $notes})
}

mutation DeleteFoodItem($id: UUID!) @auth(level: USER) {
  foodItem_delete(key: {id: $id})
}