// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD0y57M6w4v1Bi8P0sUrrbAXJx-rPardP4',
    appId: '1:172919484278:web:89be4dd7e15fe58b799457',
    messagingSenderId: '172919484278',
    projectId: 'food-dirary2',
    authDomain: 'food-dirary2.firebaseapp.com',
    storageBucket: 'food-dirary2.firebasestorage.app',
    measurementId: 'G-PKCSSCYVK5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBbaQepywzMcZlYw3AoBG2ZBZ2pQ1j8HWQ',
    appId: '1:172919484278:android:f1e3f85f5381d2ae799457',
    messagingSenderId: '172919484278',
    projectId: 'food-dirary2',
    storageBucket: 'food-dirary2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDl8Yt9k0xBx1FZdDb84DXK3_cL8hDvE1A',
    appId: '1:172919484278:ios:bc5d7cecaaa4f86a799457',
    messagingSenderId: '172919484278',
    projectId: 'food-dirary2',
    storageBucket: 'food-dirary2.firebasestorage.app',
    iosBundleId: 'com.example.foodDirary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDl8Yt9k0xBx1FZdDb84DXK3_cL8hDvE1A',
    appId: '1:172919484278:ios:bc5d7cecaaa4f86a799457',
    messagingSenderId: '172919484278',
    projectId: 'food-dirary2',
    storageBucket: 'food-dirary2.firebasestorage.app',
    iosBundleId: 'com.example.foodDirary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD0y57M6w4v1Bi8P0sUrrbAXJx-rPardP4',
    appId: '1:172919484278:web:b0a7c47eab0c028e799457',
    messagingSenderId: '172919484278',
    projectId: 'food-dirary2',
    authDomain: 'food-dirary2.firebaseapp.com',
    storageBucket: 'food-dirary2.firebasestorage.app',
    measurementId: 'G-S1VN0NQK7E',
  );
}
